# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.define :php do |config|
    config.vm.box = "wheezy64"

    config.vm.network "forwarded_port", guest: 80, host: 8080

    config.vm.network "public_network"
    #config.vm.synced_folder "../shared_data", "/vagrant_data"

    config.vm.provider "virtualbox" do |vb|
         vb.customize ["modifyvm", :id, "--memory", "512"]
    end

    config.vm.provision "shell", :path => "../../scripts/essentials.sh"
    config.vm.provision "shell", :path => "../../scripts/python.sh"

    config.vm.provision "chef_solo" do |chef|
      chef.cookbooks_path = "../../cookbooks"
      chef.add_recipe "the_silver_searcher"
      chef.add_recipe "apache2"
      chef.add_recipe "apache2::mod_php5"
      chef.add_recipe "php"
      chef.add_recipe "composer"
      #chef.json = {
      #  "apache" => {
      #    "version" => "2.4"
      #  }
      #}
    end

  end

end
