# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.define :ansible do |config|
    config.vm.box = "ARTACK/debian-jessie"
    config.vm.hostname = "ansibleclusterfuck"

    config.vm.network "forwarded_port", guest: 80, host: 8086

    config.vm.network "public_network"
    config.vm.synced_folder "../../shared_data", "/vagrant_data"
    config.vbguest.iso_path = "../VBoxGuestAdditions_5.0.20.iso"

    config.vm.provider "virtualbox" do |vb|
         vb.customize ["modifyvm", :id, "--memory", "512"]
	 # disable usb 2.0
	 vb.customize ["modifyvm", :id, "--usb", "off"]
         vb.customize ["modifyvm", :id, "--usbehci", "off"]
    end

    # By default, Vagrant will try to automatically install Ansible if it is not yet present on the guest machine
    config.vm.provision "shell", :path => "../../scripts/ansible.sh"

    # The Ansible Local provisioner requires that all the Ansible Playbook files are available on the guest machine
    config.vm.provision "ansible_local", do |ansible|
    end
 
  end

end
